
function plot_vars
% Define the GUI layout
h_figure = figure('Units','characters',...
'Position',[72 38 120 35],...
'Color',get(0,'DefaultUicontrolBackgroundColor'),...
'HandleVisibility','callback');
h_axes = axes('Units','characters',...
'Position',[10 4.5 72 26],...
'Parent',h_figure);
h_listbox_label = uicontrol(h_figure,...
'Style','text',...
'Units','characters',...
'Position',[88 29 24 2],...
'String','Select 2 Workspace Variables');
h_listbox = uicontrol(h_figure,...
'Style','listbox',...
'Units','characters',...
'Position',[88 18.5 24 10],...
'BackgroundColor','white',...
'Max',10,'Min',1,...
'Callback',@listbox_callback);
h_popup_label = uicontrol(h_figure,...
'Style','text',...
'Units','characters',...
'Position',[88 13 24 2],...
'String','Plot Type');
h_popup = uicontrol(h_figure,...
'Style','popupmenu',...
'Units','characters',...
'Position',[88 12 24 2],...
'BackgroundColor','white',...
'String',{'Plot','Bar','Stem'});
h_hold_toggle = uicontrol(h_figure,...
'Style','toggle',...
'Units','characters',...
'Position',[88 8 24 2],...
'String','Hold State',...
'Callback',{@hold_toggle_callback,h_axes});
h_plot_button = uicontrol(h_figure,...
'Style','pushbutton',...
'Units','characters',...
'Position',[88 3.5 24 2],...
'String','Create Plot',...
'Callback',{@plot_button_callback,h_listbox,h_popup,h_axes});